# -*- coding: utf-8 -*-
"""Tugas Kelompok_Algoritma Genetika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQUcMyHKZl9bSMDZKZe4xGMZiswAO5UD
"""

import random
from typing import List, Dict, Tuple

# Data Pakan
FEEDS = [
    {
        "name": "Alang-alang",
        "price": 500,
        "prdd": 0.04,
        "mp": 0.45
    },
    {
        "name": "Kacang panjang",
        "price": 2500,
        "prdd": 0.16,
        "mp": 0.60
    },
    {
        "name": "Ampas tahu",
        "price": 1500,
        "prdd": 0.20,
        "mp": 0.70
    },
    {
        "name": "Bungkil kelapa",
        "price": 3000,
        "prdd": 0.22,
        "mp": 0.70
    }
]


# nutrisi 1 ekor sapi perah/hari (kg)
REQUIRED_PRDD = 1.036
REQUIRED_MP   = 7.5

# batas bawah dan atas bobot setiap bahan pakan (kg)
GEN_MIN = 0.0
GEN_MAX = 10.0

# jika nutrisi kurang
NUTRITION_PENALTY_COEFF = 1e6

# parameter AG (didapat dari jurnal)
POP_SIZE = 100
MAX_GEN = 200
CROSSOVER_RATE = 0.3
MUTATION_RATE = 0.3

Chromosome = List[float]

# decode
def decode_chromosome(chrom: Chromosome) -> Dict[str, float]:
    total_prdd = 0.0
    total_mp = 0.0
    total_cost = 0.0

    for gene, feed in zip(chrom, FEEDS):
        total_prdd += gene * feed["prdd"]
        total_mp += gene * feed["mp"]
        total_cost += gene * feed["price"]

    return {
        "prdd": total_prdd,
        "mp": total_mp,
        "cost": total_cost,
    }


# biaya
def objective_function(chrom: Chromosome) -> float:
    totals = decode_chromosome(chrom)
    total_prdd = totals["prdd"]
    total_mp = totals["mp"]
    total_cost = totals["cost"]

    deficit_prdd = max(0.0, REQUIRED_PRDD - total_prdd)
    deficit_mp = max(0.0, REQUIRED_MP - total_mp)
    nutrition_deficit = deficit_prdd + deficit_mp

    if nutrition_deficit > 0:
        return total_cost + NUTRITION_PENALTY_COEFF * nutrition_deficit
    else:
        return total_cost

# fitness
def fitness(chrom: Chromosome) -> float:
    obj = objective_function(chrom)
    return 1.0 / (1.0 + obj)

# inisialisasi populasi
def random_gene() -> float:
    return random.uniform(GEN_MIN, GEN_MAX)


def random_chromosome() -> Chromosome:
    return [random_gene() for _ in range(len(FEEDS))]


def initialize_population() -> List[Chromosome]:
    return [random_chromosome() for _ in range(POP_SIZE)]

# crossover
def extended_intermediate_crossover(p1: Chromosome, p2: Chromosome) -> Tuple[Chromosome, Chromosome]:
    alpha = random.uniform(0, 1)

    c1 = []
    c2 = []
    for g1, g2 in zip(p1, p2):
        new_g1 = g1 + alpha * (g2 - g1)
        new_g2 = g2 + alpha * (g1 - g2)

        new_g1 = max(GEN_MIN, min(GEN_MAX, new_g1))
        new_g2 = max(GEN_MIN, min(GEN_MAX, new_g2))

        c1.append(new_g1)
        c2.append(new_g2)

    return c1, c2

# mutasi random
def mutate(chrom: Chromosome) -> Chromosome:
    mutant = chrom[:]
    for i in range(len(mutant)):
        if random.random() < MUTATION_RATE:
            r = random.uniform(-0.1, 0.1)
            mutant[i] = mutant[i] + r * (GEN_MAX - GEN_MIN)
            mutant[i] = max(GEN_MIN, min(GEN_MAX, mutant[i]))
    return mutant

# seleksi gen
def genetic_algorithm():
    population = initialize_population()

    best_chrom = None
    best_fit = float("-inf")

    for gen in range(MAX_GEN):
        fits = [fitness(ind) for ind in population]
        gen_best_idx = max(range(len(population)), key=lambda i: fits[i])
        gen_best_chrom = population[gen_best_idx]
        gen_best_fit = fits[gen_best_idx]

        if gen_best_fit > best_fit:
            best_fit = gen_best_fit
            best_chrom = gen_best_chrom[:]

        totals = decode_chromosome(best_chrom)
        print(
            f"Gen {gen:3d} | best fitness = {best_fit:.8f} | "
            f"Prdd={totals['prdd']:.4f} MP={totals['mp']:.4f} Cost={totals['cost']:.2f}"
        )

        offspring: List[Chromosome] = []

        num_offspring_cross = int(CROSSOVER_RATE * POP_SIZE)
        if num_offspring_cross % 2 == 1:
            num_offspring_cross += 1

        for _ in range(num_offspring_cross // 2):
            p1 = random.choice(population)
            p2 = random.choice(population)
            c1, c2 = extended_intermediate_crossover(p1, p2)
            offspring.append(c1)
            offspring.append(c2)

        num_offspring_mut = int(MUTATION_RATE * POP_SIZE)
        for _ in range(num_offspring_mut):
            parent = random.choice(population)
            child = mutate(parent)
            offspring.append(child)

        combined = population + offspring
        combined_fits = [(ind, fitness(ind)) for ind in combined]
        combined_fits.sort(key=lambda x: x[1], reverse=True)

        population = [ind for (ind, fit_val) in combined_fits[:POP_SIZE]]

    best_totals = decode_chromosome(best_chrom)
    return best_chrom, best_totals, best_fit

if __name__ == "__main__":
    best_chrom, totals, best_fit = genetic_algorithm()

    print("\n=== Hasil Optimasi dengan Algortima Genetika ===")
    print("Komposisi pakan (kg per bahan):")
    for gene, feed in zip(best_chrom, FEEDS):
        print(f"- {feed['name']:15s}: {gene:.4f} kg")

    print("\nTotal nutrisi & biaya:")
    print(f"Prdd (Protein) total      : {totals['prdd']:.4f} kg (target {REQUIRED_PRDD} kg)")
    print(f"MP (Martabat Pati) total  : {totals['mp']:.4f} kg (target {REQUIRED_MP} kg)")
    print(f"Biaya                     : Rp {totals['cost']:.2f}")
    print(f"\nFitness terbaik         : {best_fit:.10f}")